name:                security-manager
version:             0.1.0.0
#synopsis:
#description:
license:             GPL-3.0
author:              Mark Seemann
copyright:           2024 Mark Seemann
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  security-manager-app:
    source-dirs:      app
    main:             Main.hs
    dependencies:
    - security-manager

library:
  source-dirs: src
  ghc-options:
  - -Wall

tests:
  security-manager-test:
    main:        Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - security-manager
    - HUnit
    - test-framework
    - test-framework-hunit
    - transformers